'''
Bindings to dynamite-bud/crumsort-wasm v0.2.1.
'''

# Generated by wasmer-pack v0.7.1.

from wasmer import Store as _Store # type: ignore
from .bindings import Bindings as _Bindings

__version__ = "0.2.1"

_store = _Store()
bindings = _Bindings(_store)